Management UI | Support for Metrics Reporting Provisioning operations
5G-MAG/rt-5gms-application-provider pull request #38
Opened 2024-05-03 13:13 UTC by stojkovicv

## Description
This pull request expands `management-ui` server and GUI with the Metrics Reporting operations. Additionally, rearranges some html elements and enhances GUI design, adds browser title and favicon, increases font size for beter readability, improves error messages etc.

## List of Metrics Reporting Configurations IDs
Handling multiple MetricsReportingConfigurations requires control over the ID value of the configuration. Since there is no specific endpoint that will fetch entire list of IDs of provisioned MetricsReportingConfigurations, `management-ui` server implements a `/list_metrics_ids` endpoint.
At first, this endpoint took advantage of M1 `python` library function `metricsReportingConfigurationIds()` but significant time delay from creation of multiple MetricsReportingConfigurations until the listing of all IDs has been spotted. To address this issue, I implemeted endpoint that will query particular provisioning session directly from the Application Function, and fetch entire `metricsReportingConfigurationIds` array. With this approach there was no time delay.

Finally, the GUI allows the user the choose which MetricReportingConfiguration wants to display or remove, by listing all IDs in form of buttons, that will further conduct desired operation. In this way, complete control over the management of multiple configurations is achieved.

2024-05-07 06:42 UTC, dsilhavy reviewed
Only looking at the UI, this is very intuitive and seems to work fine based on my tests. Nice work @stojkovicv . Also, wrong input values are not accepted and a corresponding error message is shown.

One thing I notice: The metrics reporting configuration is not shown as part of the `session details`. Was this done on purpose?

2024-05-07 08:47 UTC, stojkovicv commented
Thanks @dsilhavy. That's true, good notice, `session details` has to be expanded in the UI server to show DynamicPolicies and MetricsReportingConfigurations. Related functionality in Python library is already completed, somehow I forgot to apply it to the UI.

2024-05-16 18:50 UTC, dsilhavy approved these changes

2024-05-17 09:56 UTC, davidjwbbc requested changes

2024-05-17 09:56 UTC, davidjwbbc commented on management-ui/static/m1-user-interface.js
> +    cell9.innerHTML = `<button onclick="deleteProvisioningSession('${session_id}')" class="btn btn-danger table-button">Remove</button>`;
This should just call `addSessionToTable(session_id)` to insert each provisioning session instead of repeating the code.

2024-05-20 16:53 UTC, davidjwbbc approved these changes

2024-05-21 06:10 UTC, merged