Bugfix | Web UI server-side storage
5G-MAG/rt-5gms-application-provider pull request #50
Opened 2024-08-19 16:08 UTC by stojkovicv

## Description

This PR enhances session data storage by moving it from the browser cache to server-side storage. It introduces several auxiliary endpoints and tweaks frontend functionalities to allign with the in-memory writing of the Python classes. Minor styling changes are done, as well.
The changes have been tested from two different devices to confirm consistency.

Related issue: #49

2024-08-20 10:20 UTC, davidjwbbc requested changes
There's some changes needed so that these changes respect the class interfaces for M1Session instead of trying to bypass them. Bypassing them could cause misbehaviour in the class as your bypass is not maintaining the internal data integrity maintained by the class itself. It also add the risk that future changes to the internals of the M1Session class break your code when internal data structures are changed.

2024-08-20 10:20 UTC, davidjwbbc commented on management-ui/server.py
> +    session._M1Session__provisioning_sessions.clear()
You should not be accessing protected members of a class from outside the class, please stick to using M1Session public methods to manipulate the session.

Also clearing the list of known provisioning sessions like this is a bad idea (it won't update the persistent data store for one), if you want to remove provisioning sessions then use `session.provisioningSessionDestroy()` on each known provisioning session id (`session.provisioningSessionIds()`).

2024-08-20 10:20 UTC, davidjwbbc commented on management-ui/server.py
> +            session_data['certificate_id'] = cert_id
The certificate Id will already be in the list of certificate Ids in the provisioning session after the call to `session.createNewCertificate()`, you shouldn't be setting strange dictionary members.

2024-08-20 10:20 UTC, davidjwbbc commented on management-ui/server.py
> +        session_data = session._M1Session__provisioning_sessions.get(provisioning_session_id)
Again, there are methods to access and manipulate provisioning sessions in M1Session. There is no need to bypass the class and access member variables directly.

2024-08-20 10:20 UTC, davidjwbbc commented on management-ui/server.py
> +        return {"certificate_id": session_data['certificate_id']}
You should be using `session.provisioningSessionCertificateIds(provisioning_session_id)` to retrieve a list of certificates, not inventing a single certificate store.

2024-08-22 12:41 UTC, stojkovicv commented on management-ui/server.py
> +        return {"certificate_id": session_data['certificate_id']}
There's been a unclear issue, where I receive empty list of a certificate Ids when using `session.provisioningSessionCertificateIds(provisioning_session_id)`, even though the Certificate is created. 

Another possibility is to fetch this ID directly from the AF response for provisioning session:
```
    "serverCertificateIds": [
        "f9a4cf16-58dc-41ef-8bfc-d7aaf8f810a4"
    ]
 ```

2024-08-22 13:20 UTC, stojkovicv commented on management-ui/server.py
> +        return {"certificate_id": session_data['certificate_id']}
In other words, invoking `session.provisioningSessionCertificateIds` might have an memory issue at some point, resulting always with the empty list.
Instead I call `session.certificateIds()`

2024-08-22 14:56 UTC, davidjwbbc commented on management-ui/server.py
> +        return {"certificate_id": session_data['certificate_id']}
That's a bug that should be fixed then. If something is not working as expected then feel free to raise an issue.

2024-08-22 15:01 UTC, davidjwbbc approved these changes

2024-08-23 09:26 UTC, merged